# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "NB": "00_core.ipynb",
         "CCac": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://MeherKh.github.io/nbdevtest/"

git_url = "https://github.com/MeherKh/nbdevtest/tree/master/"

def custom_doc_links(name): return None
